version: '3.8'

services:
  meshtastic-bridge:
    build: ./meshtastic-bridge
    restart: unless-stopped
    privileged: true  # Needed to access /dev/ttyUSBx
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    environment:
      - MESH_DEVICE_PATH=/dev/ttyACM0
      - GO_ROUTER_URL=http://go-router:8080/send-message
      - HEALTH_CHECK_URL=http://go-router:8080/health
      - PYTHONUNBUFFERED=1
    networks:
      - app-network

  whatsapp-bot:
    build: ./whatsapp-bot
    volumes:
      - ./wwebjs_cache:/usr/src/app/.wwebjs_cache
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network

  go-router:
    build: ./go-router
    depends_on:
      - whatsapp-bot
    ports:
      - "8081:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
