version: "3.8"

services:
  whatsapp-bot:
    build: .
    container_name: whatsapp-bot
    volumes:
      - ./wwebjs_cache:/usr/src/app/.wwebjs_cache
    environment:
      - NODE_ENV=production
    restart: unless-stopped
